include:
  - template: Code-Quality.gitlab-ci.yml

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_IID' # Run pipeline on Merge Requests
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH' # Run pipeline on 'main' branch

default:
  interruptible: true

stages:
  - build
  - test
  - publish
  - deploy

### Templates
## Runners
#

.runner_inria:
  tags:
    - ci.inria.fr # required to run on shared gitlab.inria.fr runners
.runner_workstation:
  tags:
    - workstation # local workstation machine that leverages cache
.runner_mutehost:
  tags:
    - mutehost # required to deploy

.images:
  variables:
    TAG: latest
    MUTE_IMAGE: registry.gitlab.inria.fr/coast-team/mute/mute:${TAG}
    SIGVER_IMAGE: registry.gitlab.inria.fr/coast-team/mute/mute/sigver:${TAG}

### Templates
## Docker
#

.docker_registry_access: &docker_registry_access
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_IMAGE
  after_script:
    - docker logout $CI_REGISTRY_IMAGE

.docker_deployment: &docker_deployment
  script:
    - docker-compose -p $ENV_NAME -f $COMPOSE_FILE --env-file ${COMPOSE_ENV_FILE:-""} down || true
    - docker-compose pull --include-deps mute
    - docker-compose -p $ENV_NAME -f $COMPOSE_FILE --env-file ${COMPOSE_ENV_FILE:-""} up -d

### Templates
## Cache
#

.make_node_cache: &make_node_cache
  image: docker.io/node:14
  variables:
    FF_USE_FASTZIP: "true"
    ARTIFACT_COMPRESSION_LEVEL: "fast"
    CACHE_COMPRESSION_LEVEL: "fast"
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - .cache_exists
        - .npm/
        - node_modules/
        - src/assets/jio-latest.js
        - src/assets/rsvp-2.0.4.min.js
      when: on_success
      policy: pull-push

.use_node_cache: &use_node_cache
  image: docker.io/node:14-alpine
  before_script:
    - |
      if [ ! -f .cache_exists ]; then
        npm ci --cache .npm --prefer-offline --no-audit
      fi
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules/
        - src/assets/jio-latest.js
        - src/assets/rsvp-2.0.4.min.js
      when: on_success
      policy: pull
  needs:
    - job: check_dependencies
      optional: true
    - job: change_dependencies
      optional: true

### Stage
## Build
#

check_dependencies: # runs once then quickly on lock stable
  stage: build
  extends:
    - runner_workstation
    - make_node_cache
  script:
    - |
      if [ -f .cache_exists ]; then # nothing otherwise npm ci --cache .npm --prefer-offline --no-audit
        echo "cache already exists"
      else
        npm ci --cache .npm --prefer-offline --no-audit
        echo > .cache_exists
      fi
  except:
    changes:
      - package-lock.json

change_dependencies: # updates cache on lock change
  stage: build
  extends:
    - runner_workstation
    - make_node_cache
  script:
    - npm ci --cache .npm --prefer-offline --no-audit
    - echo > .cache_exists
  only:
    changes:
      - package-lock.json

build_application:
  stage: build
  extends:
    - runner_workstation
    - use_node_cache
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  when: manual

### Stage
## Lint
#

code_quality:
  extends:
    - runner_inria
  artifacts:
    paths:
      - gl-code-quality-report.json

### Stage
## Test
#

karma:
  stage: test
  extends:
    - runner_workstation
    - use_node_cache
  image: docker.io/timbru31/node-chrome:14
  only:
    - merge_requests
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit:
        - karma.xml

.e2e:
  stage: test
  <<: [*runner_inria]
  image: docker.io/docker:dind
  only:
    - merge_requests
  variables:
    DOCKERFILE_PATH: src/e2e/Dockerfile
    NAME: ${CONTAINER}-${CI_PIPELINE_IID}
  script:
    - docker build -f $DOCKERFILE_PATH -t $IMAGE . # build image
    - | # block that deletes image on teardown
      {
        docker run --privileged -d --name $NAME $IMAGE
        sleep 10
        docker exec -w /src/mute $NAME /bin/sh start-mute-sigver-containers.sh # run sigver
        docker exec -w /src/e2e/ $NAME npm run test chromium firefox $SCENARIO true # run test scenario
        docker cp $NAME:/src/e2e/e2e.xml e2e.xml # copy report from container to host
      }
      docker rm -f $NAME || true
  artifacts:
    when: always
    reports:
      junit:
        - e2e.xml

e2e_full: # whole E2E scenario
  extends: .e2e
  variables:
    IMAGE: ci-full-scenario
    CONTAINER: ci-full-scenario-container
    SCENARIO: fullscenario
  after_script:
    - docker stop $NAME
  when: manual

e2e_online: # two users meet up on the same document and modify its content
  extends: .e2e
  variables: 
    IMAGE: ci-online-scenario
    CONTAINER: ci-online-scenario-container
    SCENARIO: online
  after_script:
    - docker stop $NAME

e2e_offline: # two previously met users are disconnected from the signaling server but can still both modify the document
  extends: .e2e
  variables:
    IMAGE: ci-offline-scenario
    CONTAINER: ci-offline-scenario-container
    SCENARIO: offline
  after_script:
    - docker stop $NAME

e2e_offline-to-online: # the document at the end is a merge of their respective modifications
  extends: .e2e
  variables:
    IMAGE: ci-offline-to-online-scenario
    CONTAINER: ci-offline-to-online-scenario-container
    SCENARIO: offline-to-online
  retry: 2

### Stage
## Publish
#

.build_docker_image:
  image: docker.io/docker:dind # needs > 19.03
  stage: publish
  extends:
    - docker_registry_access
    - runner_workstation
    - images
  script:
    - docker-compose build mute
    - docker push "${MUTE_IMAGE}"

build_latest_docker_image:
  extends: .build_docker_image
  only:
    - main
  except:
    - schedules

build_release_docker_image:
  extends: .build_docker_image
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  variables:
    TAG: $CI_COMMIT_TAG

build_sigver_docker_image:
  extends: .build_docker_image
  script:
    - docker-compose build sigver
    - docker push "${SIGVER_IMAGE}"
  rules:
    - if: $SIGVER == "True" # meant to be triggered by schedule

### Stage
## Deployment
#

.deploy_to:
  image: docker.io/docker:dind # needs > 19.03
  stage: deploy
  extends:
    - docker_registry_access
    - docker_deployment
    - runner_mutehost
  variables:
    COMPOSE_FILE: docker-compose.yml

deploy_to_production:
  extends: .deploy_to
  needs:
    - job: build_release_docker_image
  rules:
    - if: $CI_COMMIT_TAG && $CI_DEPLOY_FREEZE == null
      when: on_success
  variables:
    TAG: $CI_COMMIT_TAG
    ENV_NAME: production
    COMPOSE_ENV_FILE: conf/gitlab-ci/production.env
  environment:
    name: production
    url: https://mutehost.loria.fr
  resource_group: production

deploy_to_test:
  extends: .deploy_to
  needs:
    - job: build_latest_docker_image
  only:
    - main
  variables:
    ENV_NAME: test
    COMPOSE_ENV_FILE: conf/gitlab-ci/test.env
  environment:
    name: test/default
    url: https://mutehost.loria.fr:8004
  resource_group: test
