include:
  - template: Code-Quality.gitlab-ci.yml
  - local: 'conf/gitlab-ci/*.yaml'

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_IID' # Run pipeline on Merge Requests
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH' # Run pipeline on 'main' branch

default:
  interruptible: true

stages:
  - build # see conf/gitlab-ci/build.gitlab-ci.yml
  - test # see conf/gitlab-ci/test.gitlab-ci.yml
  - publish # see conf/gitlab-ci/publish.gitlab-ci.yml
  - deploy # see conf/gitlab-ci/deploy.gitlab-ci.yml

.runner_inria:
  tags:
    - ci.inria.fr # required to run on shared gitlab.inria.fr runners
.runner_workstation:
  tags:
    - workstation # local workstation machine that leverages cache
.runner_mutehost:
  tags:
    - mutehost # required to deploy
