include:
  - template: Code-Quality.gitlab-ci.yml
  - local: conf/gitlab-ci/*.gitlab-ci.yml

workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: $CI_MERGE_REQUEST_IID # Run pipeline on Merge Requests
      variables:
        PIPELINE_NAME: 'Test pipeline for MR $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
    - if: $CI_COMMIT_TAG
      variables:
        PIPELINE_NAME: 'Release pipeline for $CI_COMMIT_TAG'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run pipeline on 'main' branch
      variables:
        PIPELINE_NAME: 'Publication pipeline'

default:
  interruptible: true

stages:
  - build # see conf/gitlab-ci/build.gitlab-ci.yml
  - test # see conf/gitlab-ci/test.gitlab-ci.yml
  - publish # see conf/gitlab-ci/publish.gitlab-ci.yml
  - deploy # see conf/gitlab-ci/deploy.gitlab-ci.yml
