### Stage
## Publish
#

.build_docker_image:
  image: docker.io/docker:dind # needs > 19.03
  stage: publish
  extends:
    - .docker_registry_access
    - .runner_workstation
    - .images
  script:
    - docker-compose build mute
    - docker push "${MUTE_IMAGE}"

build_latest_docker_image:
  extends:
    - .build_docker_image
    - .rules_latest
  except:
    - schedules

build_release_docker_image:
  extends:
    - .build_docker_image
    - .rules_release
  variables:
    TAG: $CI_COMMIT_TAG

build_sigver_docker_image:
  extends:
    - .build_docker_image
    - .rules_sigver
  script:
    - docker-compose build sigver
    - docker push "${SIGVER_IMAGE}"