include:
  - local: 'conf/gitlab-ci/runners.gitlab-ci.yml'
  - local: 'conf/gitlab-ci/rules.gitlab-ci.yml'

.build_docker_image:
  image: docker.io/docker:dind # needs > 19.03
  stage: publish
  extends:
    - .docker_registry_access
    - .runner_workstation
    - .images
  script:
    - docker-compose build mute
    - docker push "${MUTE_IMAGE}"

### Stage
## Publish
#

build_latest_docker_image:
  extends:
    - .build_docker_image
    - .rules_latest
  except:
    - schedules

build_release_docker_image:
  extends:
    - .build_docker_image
    - .rules_release
  variables:
    TAG: $CI_COMMIT_TAG

build_sigver_docker_image:
  extends:
    - .build_docker_image
    - .rules_sigver
  script:
    - docker-compose build sigver
    - docker push "${SIGVER_IMAGE}"

build_mute_with_netflux_and_sigver_docker_images:
  extends:
    - .build_docker_image
    - .rules_latest
  variables:
    TAG: netflux
    BUILD_TARGET: ':netflux'
    SIGVER_DOCKERFILE: conf/docker/DockerfileSigver
  after_script:
    - docker-compose build sigver
    - docker push "${SIGVER_IMAGE}"

build_review_environment_docker_image:
  extends:
    - .build_docker_image
    - .rules_deploy_to_review_environment
  variables:
    TAG: review-${CI_COMMIT_REF_SLUG}
    BUILD_TARGET: ':review'
    SIGVER_DOCKERFILE: conf/docker/DockerfileWebRTCStarSignalingServer
  before_script:
    - !reference [.prepare_review_variables_publish, before_script]
    - !reference [.docker_registry_access, before_script]
  after_script:
    - docker-compose build sigver
    - docker push "${SIGVER_IMAGE}"

.prepare_review_variables_publish:
  before_script:
    # Preparing variables for building app
    - json={\"reviewBranch\":\"${TAG}\"}
    - echo $json > conf/gitlab-ci/reviewEnv.json
