#
# Retry a job automatically if it fails (2 times)
#
.retry:
  retry: 2

#
# Publication rules
#
.rules_latest:
  only:
    - main
.rules_release:
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
.rules_sigver:
  rules:
    - if: $SIGVER == "True" # meant to be triggered by schedule

#
# Deployment rules
#
.rules_deploy_to_production:
  rules:
    - if: $CI_COMMIT_TAG && $CI_DEPLOY_FREEZE == null
      when: on_success

.rules_deploy_to_test:
  only:
    - main