version: '3.9'

services:
  mute:
    depends_on:
      - pulsar

  pulsar:
    image: docker.io/apachepulsar/pulsar:2.6.0
    ports:
      - ${PULSAR_WEB_PORT:-8080}:8080
      - ${PULSAR_PORT:-6650}:6650
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone

volumes:
  pulsardata:
  pulsarconf: